# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: mii-ig-modul-patho
canonical: https://www.medizininformatik-initiative.de/fhir/ext/modul-patho
title: "MII IG Modul Patho"
name: MII_IG_Modul_Patho
language: de-DE
status: active
experimental: false
version: 1.0.0
date: "2024-12-10"
fhirVersion: 4.0.1
copyrightYear: 2021+
packageId: de.medizininformatikinitiative.kerndatensatz.patho
releaseLabel: ci-build
publisher:
  name: Medizininformatik-Initiative
  url: https://www.medizininformatik-initiative.de/
  email: info@medizininformatik-initiative.de
FSHOnly: false
# Don't forget to add further dependencies if necessary!
dependencies:
  # de.basisprofil.r4: 1.5.0
  de.medizininformatikinitiative.kerndatensatz.meta: 2026.0.x
  de.medizininformatikinitiative.kerndatensatz.biobank: 2026.0.0-ballot1
  de.medizininformatikinitiative.kerndatensatz.diagnose: 2026.0.x
  de.gematik.isik: 5.1.0
  hl7.fhir.us.mcode: 4.0.0-ballot

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
